"""By when should this be done, in THIS opening.

Design: docs/notes/design.opening-development-signals.md
Evidence: docs/notes/experiments.e59-strong-player-expectation.md

The author's instruction:

    "I don't want this to be built by peer reference but by better players who
    usually know the opening... The expected moves are not going to be the exact
    average or median of the higher ranked players but average/median + 1/2."

So there are **two populations doing two different jobs**. This module holds the
first: an expectation derived from 5,917 rated games by the top 100 Lichess
rapid players, per opening family and colour. The second -- how *often* a player
misses it compared with their own band -- is the peer reference, and it lives
where every other claim's comparison lives.

**Nothing here is asserted.** *"Castle by move 10"* would be a teaching heuristic
and unfalsifiable, which R-03 forbids; these numbers are medians of real games
and are regenerated by `experiments/e58-opening-development/build_norms.py`.

**The tolerance is load-bearing, not a safety margin.** A threshold at the bare
median flags half the population it came from, by construction -- including half
of the strong players. `TOLERANCE_PLIES` is what turns *above average* into
*unusually late*.
"""

from __future__ import annotations

import json
import math
import statistics
from dataclasses import dataclass
from pathlib import Path

import chess

DEFAULT_NORMS = Path(__file__).resolve().parent.parent / "data" / "openings" / "development-norms.json"

# +2 moves, the author's upper setting. In plies, because that is what the
# measurement speaks.
TOLERANCE_PLIES = 4

# Below this a median is a coincidence rather than a norm, and the opening falls
# back to the player's own behaviour.
MIN_STRONG_GAMES = 20

# A median of two numbers is a difference, not a norm. Fewer distinct openings
# than this and the fallback stays silent rather than inventing a baseline.
MIN_OWN_OPENINGS = 3


@dataclass(frozen=True)
class Norm:
    """What players who know this opening do in it."""

    castle_ply: float | None
    ready_ply: float | None
    games: int


@dataclass(frozen=True)
class Verdict:
    """Whether one game was late, and what it was judged against.

    `basis` is carried because the two bases answer **different questions** and a
    report must not blur them: `"strong"` says *you are late by this opening's
    standard*, `"own"` says only *you are later here than in your own other
    openings*. The second cannot say the timing is wrong.
    """

    late_castling: bool | None
    slow_development: bool | None
    basis: str  # "strong" | "own" | "none"


class DevelopmentNorms:
    """Per-opening expectations, with the author's own-median fallback."""

    def __init__(self, norms: dict[tuple[str, bool], Norm]) -> None:
        self._norms = norms

    def __len__(self) -> int:
        return len(self._norms)

    @classmethod
    def load(cls, path: Path | str = DEFAULT_NORMS) -> DevelopmentNorms:
        raw = json.loads(Path(path).read_text(encoding="utf-8"))
        norms = {}
        for row in raw["norms"]:
            key = (row["family"], row["colour"] == "white")
            norms[key] = Norm(
                castle_ply=row["castle_ply"],
                ready_ply=row["ready_ply"],
                games=row["games"],
            )
        return cls(norms)

    def norm_for(self, family: str, colour: chess.Color) -> Norm | None:
        """The expectation for this opening, or `None` if nobody strong plays it."""
        norm = self._norms.get((family, bool(colour)))
        if norm is None or norm.games < MIN_STRONG_GAMES:
            return None
        return norm

    def judge(self, family: str, colour: chess.Color, development) -> Verdict:
        """Was this game late, by the strong players' standard for this opening?

        **Never finishing is the most extreme way of being past the expectation**,
        not a missing value -- treating it as missing would drop exactly the
        games the claim is about, which is the censoring the design refuses.
        """
        norm = self.norm_for(family, colour)
        if norm is None:
            return Verdict(None, None, "none")
        return Verdict(
            late_castling=_past(development.castled_at, norm.castle_ply),
            slow_development=_past(development.ready_at, norm.ready_ply),
            basis="strong",
        )

    def judge_against_self(self, developments, development) -> Verdict:
        """The fallback: this game against the player's own usual timing.

        > *"The peer calculation here for some players that play the openings
        > that no other players from the corpus play will be calculated against
        > their own average/median, not by something that can be explained by
        > population."*

        `developments` is the player's own games in openings that DO have a
        strong-player norm -- their established habit. Comparing an unusual
        opening against the player's whole history including itself would let one
        strange opening set its own baseline.
        """
        castles = [d.castled_at for d in developments if d.castled_at is not None]
        readies = [d.ready_at for d in developments if d.ready_at is not None]
        if len(castles) < MIN_OWN_OPENINGS or len(readies) < MIN_OWN_OPENINGS:
            return Verdict(None, None, "none")
        return Verdict(
            late_castling=_past(development.castled_at, statistics.median(castles)),
            slow_development=_past(development.ready_at, statistics.median(readies)),
            basis="own",
        )


def _past(actual: int | None, expected: float | None) -> bool | None:
    """Did this game exceed the expectation? `None` when there is no expectation."""
    if expected is None:
        return None
    if actual is None:
        return True  # never got there at all
    return actual > expected + TOLERANCE_PLIES


def survival_median(reached: list[int], never: int) -> float | None:
    """The ply by which half the games got there, counting the ones that never did.

    A median over only the games that succeeded is censored: Bishop's Opening
    castles on move 11 among the games that castle, and 47 % never castle, so 11
    is not the norm. Games that never got there sort after every game that did,
    and if they carry the midpoint the answer is `None`.
    """
    total = len(reached) + never
    if total == 0:
        return None
    ordered = sorted(reached)
    middle = (total - 1) // 2
    if middle >= len(ordered):
        return None
    if total % 2 == 1:
        return float(ordered[middle])
    upper = middle + 1
    if upper >= len(ordered):
        return None
    return (ordered[middle] + ordered[upper]) / 2


def move_number(ply: float) -> int:
    """Plies are how the board counts; players speak in moves."""
    return math.ceil(ply / 2)
