"""Which claims may carry a comparison between players, and which may not.

Spec: docs/notes/design.claims-that-do-not-separate.md § D1

The peer comparison asserts *"you do this more than your peers"*. That sentence
needs players to actually differ. [[experiments.e84-band-references]] tested every shipped claim for whether
players **within one rating band** differ by more than binomial sampling noise,
and found sixteen asserted claims on which they do not.

`allowed_motif.fork` sits at 3.3 % across 83 players with about 248 errors each.
If every player's true rate were exactly 3.3 %, measured rates would still
scatter roughly 2-5 % by chance. Somebody lands in the top decile, is told they
are fork-prone, and is average next month. That is the unfalsifiable coaching
V8 exists to prevent.

**Nothing here retires a detector.** These claims keep firing, keep costing win
probability, and keep citing the player's own games. What this register removes
is the comparison, and the rank the baseline fallback would hand it instead.

Absence from the register means *not screened*, which is not evidence of
anything -- `separates` therefore defaults to True. Muting on absence would
silence every claim E83 never reached.
"""

from __future__ import annotations

from dataclasses import dataclass

from chesscoach.peers import PeerReference

SOURCE = "experiments.e84-band-references"


@dataclass(frozen=True)
class Separation:
    """Why one claim cannot carry a comparison, with the numbers that say so."""

    dispersion: float
    p: float
    # The smallest between-player difference the screen could have detected, as
    # the ratio of a player one SD above the mean to one at the mean. A small
    # value with dispersion near 1.0 is a positive finding of flatness; a large
    # one means the screen was blind and the verdict is "not shown".
    smallest_visible: float
    players: int
    conclusive: bool
    source: str = SOURCE


# 24 claims; 19 conclusive, 5 inconclusive
# Generated by experiments/e84-band-references/register.py
# Screened within band on peers-e84: three bands, two speeds, denominator A.
DOES_NOT_SEPARATE: dict[str, Separation] = {
    "executed_motif.hangingPiece.own": Separation(1.28, 0.0932, 1.04, 50, conclusive=True),  # 1400-1800|blitz
    "concedes_weakness.any.own": Separation(1.16, 0.209, 1.13, 50, conclusive=True),  # 1400-1800|blitz
    "out_of_book.Queen's Pawn Game.own": Separation(1.33, 0.168, 1.13, 17, conclusive=True),  # 1400-1800|rapid
    "missed_motif.pin.own": Separation(1.22, 0.164, 1.14, 40, conclusive=True),  # 1400-1800|blitz
    "concedes_weakness.isolated.own": Separation(1.07, 0.337, 1.17, 50, conclusive=True),  # 1400-1800|blitz
    "missed_motif.discoveredAttack.own": Separation(0.85, 0.683, 1.21, 28, conclusive=True),  # 1400-1800|blitz
    "allows_square.any.own": Separation(1.10, 0.29, 1.22, 50, conclusive=True),  # 1400-1800|blitz
    "allowed_motif.pin.own": Separation(1.32, 0.0654, 1.22, 50, conclusive=True),  # 1400-1800|blitz
    "missed_motif.fork.own": Separation(1.34, 0.142, 1.23, 21, conclusive=True),  # 1400-1800|blitz
    "allowed_motif.discoveredAttack.own": Separation(1.29, 0.0825, 1.24, 50, conclusive=True),  # 1400-1800|blitz
    "concedes_weakness.backward.own": Separation(1.20, 0.159, 1.25, 50, conclusive=True),  # 1400-1800|blitz
    "missed_motif.hangingPiece.own": Separation(1.24, 0.124, 1.27, 50, conclusive=True),  # 1400-1800|blitz
    "out_of_book.Caro-Kann Defense.own": Separation(1.40, 0.165, 1.27, 12, conclusive=True),  # 1600-2000|rapid
    "executed_motif.pin.own": Separation(1.09, 0.321, 1.27, 40, conclusive=True),  # 1400-1800|blitz
    "executed_motif.fork.own": Separation(1.36, 0.132, 1.28, 21, conclusive=True),  # 1400-1800|blitz
    "executed_motif.discoveredAttack.own": Separation(0.89, 0.63, 1.28, 28, conclusive=True),  # 1400-1800|blitz
    "opening_pawn_error.any.own": Separation(1.35, 0.053, 1.29, 50, conclusive=True),  # 1400-1800|blitz
    "allows_pressure.king.own": Separation(1.14, 0.23, 1.34, 50, conclusive=True),  # 1400-1800|blitz
    "allowed_motif.skewer.own": Separation(1.07, 0.351, 1.34, 48, conclusive=True),  # 1400-1800|blitz
    "allows_square.rook_seventh.own": Separation(0.82, 0.804, 1.35, 50, conclusive=False),  # 1400-1800|blitz
    "sacrificed_for_attack.own_move.own": Separation(1.24, 0.123, 1.39, 50, conclusive=False),  # 1400-1800|blitz
    "out_of_book.Italian Game.own": Separation(1.64, 0.0673, 1.41, 14, conclusive=False),  # 1400-1800|blitz
    "allowed_motif.capturingDefender.own": Separation(0.32, 1, 1.56, 34, conclusive=False),  # 1400-1800|rapid
    "allowed_motif.backRankMate.own": Separation(0.25, 0.993, 1.82, 12, conclusive=False),  # 1400-1800|blitz
}


def why_not(claim_key: str) -> Separation | None:
    """The evidence against comparing this claim, or None if there is none."""
    return DOES_NOT_SEPARATE.get(PeerReference.canonical(claim_key))


def separates(claim_key: str) -> bool:
    """Whether players differ on this claim by more than sampling noise.

    Keys arrive both ways: sections pass `kind.subject`, the reference stores
    `kind.subject.own`. Canonicalising through `PeerReference` is what stops
    this repeating I-10, where exactly that mismatch muted four shipped claims.
    """
    return why_not(claim_key) is None
